name: XcodeGenWithPods
targets:
  XcodeGenWithPods:
    type: application
    platform: iOS
    sources: [XcodeGenWithPods]
    templates: [CocoaPods]

targetTemplates:
  CocoaPods:
    configFiles:
      Debug: Pods/Target Support Files/Pods-${target_name}/Pods-${target_name}.debug.xcconfig
      Release: Pods/Target Support Files/Pods-${target_name}/Pods-${target_name}.release.xcconfig
    dependencies:
      - framework: "Pods_${target_name}.framework"
        implicit: true
        embed: false
    preBuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        path: /bin/sh
        script: |
          diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
          if [ $? != 0 ] ; then
              # print error to STDERR
              echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." >&2
              exit 1
          fi
          # This output is used by Xcode 'outputs' to avoid re-running this script phase.
          echo "SUCCESS" > "${SCRIPT_OUTPUT_FILE_0}"
        inputFiles:
          - "${PODS_PODFILE_DIR_PATH}/Podfile.lock"
          - "${PODS_ROOT}/Manifest.lock"
        outputFiles:
          - "$(DERIVED_FILE_DIR)/Pods-${target_name}-checkManifestLockResult.txt"
    postCompileScripts:
      - name: "[CP] Embed Pods Frameworks"
        path: /bin/sh
        script: |
          SCRIPT="${PODS_ROOT}/Target Support Files/Pods-${target_name}/Pods-${target_name}-frameworks.sh"
          if [ -e $SCRIPT ]; then
            $SCRIPT
          fi
      - name: "[CP] Copy Pods Resources"
        path: /bin/sh
        script: |
          SCRIPT="${PODS_ROOT}/Target Support Files/Pods-${target_name}/Pods-${target_name}-resources.sh"
          if [ -e $SCRIPT ]; then
            $SCRIPT
          fi
